name: Test HTML Page

on:
  push:
    branches:
      - main
      - test_html
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Fix permissions for Jest binary
      - name: Fix permissions for Jest
        run: chmod +x ./node_modules/.bin/jest

      # Step 5: List installed npm packages (for debugging)
      - name: List installed npm packages
        run: npm list --depth=0

      # Step 6: Run tests using Jest
      - name: Run tests
        run: npx jest
