name: Test HTML Page

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use compatible Node.js version

      - name: Clean npm cache and install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: Install Jest globally (to ensure it can be found)
        run: npm install -g jest

      - name: Fix Jest permissions
        run: chmod +x ./node_modules/.bin/jest

      - name: List installed npm packages
        run: npm list --depth=0

      - name: Run tests
        run: npm test
