name: Test HTML Page

on:
  push:
    branches:
      - main
      - test_html
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Clean npm cache and remove old dependencies
      - name: Clean npm cache and reinstall dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
      # Step 4: List installed npm packages (for debugging)
      - name: List installed npm packages
        run: npm list --depth=0

      # Step 5: Run tests using Jest (npx will find Jest installed in node_modules)
      - name: Run tests
        run: npx jest